package com.lc.leetcode;

/**
 * Created by caoling on 2016/11/4.
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */
public class T398 {

    public static char findTheDifference(String s, String t) {
        int[] sData = new int[123];
        for (char c : s.toCharArray()) {
            int pos = (int) c;
            sData[pos]++;
        }
        for (char c : t.toCharArray()) {
            int pos = (int) c;
            if (sData[pos] == 0) {
                return c;
            } else {
                sData[pos]--;
            }
        }
        return t.charAt(t.length());
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        System.out.println(findTheDifference(s, t));

    }
}
